// Code generated by protoc-gen-go-errors. DO NOT EDIT.
package errorspb

import (
	"fmt"
	"google.golang.org/protobuf/proto"
)

func (e *ApplicationError) Error() string {
	switch v := e.Kind.(type) {
	case *ApplicationError_Config:
		return v.Config.Error()
	case *ApplicationError_Io:
		return v.Io.Error()
	case *ApplicationError_Other:
		return v.Other.Error()
	default:
		return "unknown error"
	}
}

func (e *ApplicationError) Unwrap() error {
	switch v := e.Kind.(type) {
	case *ApplicationError_Config:
		if v.Config != nil {
			return v.Config
		}
	case *ApplicationError_Io:
		if v.Io != nil {
			return v.Io
		}
	case *ApplicationError_Other:
		if v.Other != nil {
			return v.Other
		}
	}
	return nil
}

type fromApplicationError interface {
	error
	proto.Message
	applicationErrorMarker()
}

func (e *ApplicationError) From(leaf fromApplicationError) *ApplicationError {
	switch v := leaf.(type) {
	case *ConfigError:
		return &ApplicationError{Kind: &ApplicationError_Config{
			Config: v,
		}}
	case *IOError:
		return &ApplicationError{Kind: &ApplicationError_Io{
			Io: v,
		}}
	case *OtherError:
		return &ApplicationError{Kind: &ApplicationError_Other{
			Other: v,
		}}
	default:
		panic(fmt.Sprintf("protoc-gen-go-errors: %T is not one of the error messages of ApplicationError", leaf))
	}
}

func (e *ApplicationError) FromConfigError(leaf *ConfigError) *ApplicationError {
	return &ApplicationError{Kind: &ApplicationError_Config{
		Config: leaf,
	}}
}

func (e *ApplicationError) FromIOError(leaf *IOError) *ApplicationError {
	return &ApplicationError{Kind: &ApplicationError_Io{
		Io: leaf,
	}}
}

func (e *ApplicationError) FromOtherError(leaf *OtherError) *ApplicationError {
	return &ApplicationError{Kind: &ApplicationError_Other{
		Other: leaf,
	}}
}

func (e *ConfigError) Error() string {
	return fmt.Sprintf("invalid config: %v=%v", e.GetKey(), e.GetValue())
}

func (e *ConfigError) Unwrap() error {
	return nil
}

func (*ConfigError) applicationErrorMarker() {}

func (e *IOError) Error() string {
	return fmt.Sprintf("could not read %v: %v", e.GetPath(), e.GetCause())
}

func (e *IOError) Unwrap() error {
	if v := e.GetCause(); v != nil {
		return v
	}
	return nil
}

func (*IOError) applicationErrorMarker() {}

func (e *NotFoundError) Error() string {
	return fmt.Sprintf("not found: %v", e.GetEntity())
}

func (e *NotFoundError) Unwrap() error {
	return nil
}

func (e *OtherError) Error() string {
	return fmt.Sprintf("%v", e.GetMessage())
}

func (e *OtherError) Unwrap() error {
	return nil
}

func (*OtherError) applicationErrorMarker() {}
