// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: errors/options.proto

package errors

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var file_errors_options_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         51234,
		Name:          "errors.display",
		Tag:           "bytes,51234,opt,name=display",
		Filename:      "errors/options.proto",
	},
}

// Extension fields to descriptorpb.MessageOptions.
var (
	// optional string display = 51234;
	E_Display = &file_errors_options_proto_extTypes[0]
)

var File_errors_options_proto protoreflect.FileDescriptor

const file_errors_options_proto_rawDesc = "" +
	"\n" +
	"\x14errors/options.proto\x12\x06errors\x1a google/protobuf/descriptor.proto:;\n" +
	"\adisplay\x12\x1f.google.protobuf.MessageOptions\x18\xa2\x90\x03 \x01(\tR\adisplayB4Z2github.com/varunbpatil/protoc-gen-go-errors/errorsb\x06proto3"

var file_errors_options_proto_goTypes = []any{
	(*descriptorpb.MessageOptions)(nil), // 0: google.protobuf.MessageOptions
}
var file_errors_options_proto_depIdxs = []int32{
	0, // 0: errors.display:extendee -> google.protobuf.MessageOptions
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	0, // [0:1] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_errors_options_proto_init() }
func file_errors_options_proto_init() {
	if File_errors_options_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_errors_options_proto_rawDesc), len(file_errors_options_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 1,
			NumServices:   0,
		},
		GoTypes:           file_errors_options_proto_goTypes,
		DependencyIndexes: file_errors_options_proto_depIdxs,
		ExtensionInfos:    file_errors_options_proto_extTypes,
	}.Build()
	File_errors_options_proto = out.File
	file_errors_options_proto_goTypes = nil
	file_errors_options_proto_depIdxs = nil
}
